version: "3"
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'rivereyes'
      MYSQL_PASSWORD : 'root'
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'rivereyes'
      MYSQL_PASSWORD : 'root'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 15


